Fix compile error on MSVC 2019. MSVC does not support initializing the rb_data_type_t structure from a pointer. Error is:
ruby_wrapper.c(359): error C2099: initializer is not a constant
ruby_wrapper.c(359): error C4047: 'initializing': 'void *' differs in levels of indirection from 'int'

Fixed by moving code to pycall_init_ruby_wrapper.